modLoader = "javafml"
loaderVersion = "[1,)"
license = "MIT"
issueTrackerURL = "https://github.com/yourusername/industriacreate/issues"

[[mods]]
modId = "industriacreate"
version = "1.0.0"
displayName = "Industria Create"
authors = "Jerkey"
description = '''
Extend Create by adding industrial workers.
'''

[[dependencies.industriacreate]]
modId = "forge"
mandatory = true
versionRange = "[47.4.0,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.industriacreate]]
modId = "minecraft"
mandatory = true
versionRange = "[1.20.1,1.21)"
ordering = "NONE"
side = "BOTH"

[[dependencies.industriacreate]]
modId = "create"
mandatory = true
versionRange = "[0.6.0,)"
ordering = "AFTER"
side = "BOTH"